
export const shopifyFieldDescriptions: { [key: string]: string } = {
  "Handle": "A unique identifier for the product. Created automatically from the title if not provided. Used in URLs for your products.",
  "Title": "The name of the product shown to customers.",
  "Body (HTML)": "A detailed description of the product. Supports HTML formatting for rich text.",
  "Vendor": "The manufacturer, wholesaler, or other vendor of the product.",
  "Product Category": "The category of the product used for SEO and product organization.",
  "Type": "A categorization used to organize products into groups.",
  "Tags": "Keywords used to filter, search, and organize products. Separate multiple tags with commas.",
  "Published": "Set to TRUE to make the product visible in your store, or FALSE to hide it.",
  "Option1 Name": "The name of your first product option (e.g., 'Color', 'Size').",
  "Option1 Value": "The value for your first option (e.g., 'Red', 'Small').",
  "Option2 Name": "The name of your second product option.",
  "Option2 Value": "The value for your second option.",
  "Option3 Name": "The name of your third product option.",
  "Option3 Value": "The value for your third option.",
  "Variant SKU": "A unique identifier for tracking inventory of this specific variant.",
  "Variant Grams": "The weight of the variant in grams.",
  "Variant Inventory Tracker": "The system used to track inventory ('shopify' or blank).",
  "Variant Inventory Qty": "The number of items you have in stock for this variant.",
  "Variant Inventory Policy": "What happens when a variant is out of stock ('deny' or 'continue').",
  "Variant Fulfillment Service": "The fulfillment service that will ship this variant.",
  "Variant Price": "The price that customers pay for this variant.",
  "Variant Compare At Price": "Original price before discount. Shows as crossed-out price.",
  "Variant Requires Shipping": "Set to TRUE if this variant needs to be shipped.",
  "Variant Taxable": "Set to TRUE if taxes should be charged on this variant.",
  "Variant Barcode": "The barcode, ISBN, UPC, or GTIN number for the variant.",
  "Image Src": "The URL or file path of the product image.",
  "Image Position": "The order of the image in the product's gallery (1, 2, 3, etc.).",
  "Image Alt Text": "Alternative text for the image, important for accessibility.",
  "Gift Card": "Set to TRUE if this product is a gift card.",
  "SEO Title": "The page title used for SEO (defaults to product title if blank).",
  "SEO Description": "Meta description for search engines. Should be under 160 characters.",
  "Status": "The status of the product (active, archived, or draft)."
};
