// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaliiftkyeqvapjkmaio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphbGlpZnRreWVxdmFwamttYWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4ODQ4NDAsImV4cCI6MjA1NDQ2MDg0MH0.qCUZa0cCn1ukkHE3HPujSdcWXtr-hj88jLjF3uPmLpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);